apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: food-delivery-notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3007
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3007"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/notifications"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 3007
    targetPort: 3007
  type: ClusterIP 