apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: food-delivery-order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3003"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/orders"
        - name: RESTAURANT_SERVICE_URL
          value: "http://restaurant-service:3006"
        - name: DELIVERY_SERVICE_URL
          value: "http://delivery-service:3005"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3007"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP 