apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: food-delivery-payment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3004"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/payments"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP 