apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: food-delivery-restaurant-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3006
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3006"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/restaurants"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
  - port: 3006
    targetPort: 3006
  type: ClusterIP 