version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://authentication-service:3001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3006
      - ORDER_SERVICE_URL=http://order-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - DELIVERY_SERVICE_URL=http://delivery-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
    depends_on:
      - authentication-service
      - order-service
      - payment-service
      - delivery-service
      - restaurant-service
      - notification-service

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=HGFHGEAD%D^ghggjhd%dsgj

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - JWT_SECRET=HGFHGEAD%D^ghggjhd%dsgj
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3006
      - DELIVERY_SERVICE_URL=http://delivery-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
      - AUTH_SERVICE_URL=http://authentication-service:3001
      - PAYMENT_SERVICE_URL=http://localhost:3004

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - JWT_SECRET=HGFHGEAD%D^ghggjhd%dsgj
      - ORDER_SERVICE_URL=http://localhost:3003
      - DELIVERY_SERVICE_URL=http://localhost:3005
      - STRIPE_SECRET_KEY=sk_test_51RGXpNPsJKAfjT1p5U66HxUeNUZMLmChoERLW9fF7U89LwPjK4ne9LCnPIqPdQQw7d5jOwRzI8c3G9UKoE4McA5g00qZjW7cnp
      - FRONTEND_URL=http://localhost:5173

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - JWT_SECRET=HGFHGEAD%D^ghggjhd%dsgj
      - ORDER_SERVICE_URL=http://localhost:3003
      - AUTH_SERVICE_URL=http://localhost:3001

  restaurant-service:
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - JWT_SECRET=HGFHGEAD%D^ghggjhd%dsgj

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
      - JWT_SECRET=HGFHGEAD%D^ghggjhd%dsgj
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=eatease.online@gmail.com
      - EMAIL_PASS=nutzgvmbmfbuuexe
      - TWILIO_ACCOUNT_SID=AC9f4d7b04168f4407f1986917e63ff45d
      - TWILIO_AUTH_TOKEN=eddc82dbacdf5b2d687e6a37825ca743
      - TWILIO_PHONE_NUMBER=+17756183906
      - TWILIO_WHATSAPP_NUMBER=+14155238886
      - TWILIO_WHATSAPP_SANDBOX_NUMBER=+14155238886
