version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://authentication-service:3001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3006
      - ORDER_SERVICE_URL=http://order-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - DELIVERY_SERVICE_URL=http://delivery-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
    depends_on:
      - authentication-service
      - order-service
      - payment-service
      - delivery-service
      - restaurant-service
      - notification-service

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3006
      - DELIVERY_SERVICE_URL=http://delivery-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
      - AUTH_SERVICE_URL=http://authentication-service:3001

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005

  restaurant-service:
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
