apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  jwt-secret: base64encodedsecretkey  # Replace with actual base64 encoded secret
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-password: base64encodedpassword  # Replace with actual base64 encoded password 