version: "3.8"

services:
  api-gateway:
    build: .
    container_name: api-gateway
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - order-service
      - restaurant-service
      - delivery-service
    environment:
      - PORT=5000
      - JWT_SECRET=your_secret_key
      - AUTH_SERVICE_URL=http://auth-service:5001
      - ORDER_SERVICE_URL=http://order-service:5002
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5003
      - DELIVERY_SERVICE_URL=http://delivery-service:5004
