services:
  restaurant-service:
    build: .
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurant-service
      - JWT_SECRET=your_secret_key
