version: "3.8"
services:
  restaurant-service:
    build: ./backend/restaurant-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://Nadil:Nadil111@cluster.tejhn.mongodb.net/Restaurant?retryWrites=true&w=majority&appName=Cluster
      - PORT=3003
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
